### ISSUE TITLE
Add way to disable using java from opscode

### ISSUE THREAD

**Issue by ghost** [greglu/dropwizard-cookbook#2]
Is there a way we can stop having dropwizard-cookbook install java itself?  there are cases when we want to more tightly control java version and artifacts of java...  having dropwizard-cookbook just include it and run it by default may cause issues and at some cases a messed up system.

is there a way we can implement like  install_java = true|false attribute  we can then toggle on our end ?

**Comment by greglu** [comment]
Ya this was silly. I haven't been maintaining this but recently I needed to update the cookbook again. With the release of [v2.0.0](https://supermarket.chef.io/cookbooks/dropwizard/), this cookbook will no longer handle any java installation. You just need to pass it a path to the java binary.
