### ISSUE TITLE
Use chef-pleaserun for init service management

### ISSUE THREAD

**Issue by patcon** [greglu/dropwizard-cookbook#3]
I haven't used it yet myself, but it's on my mind whenever I see a cookbook managing init scripts :)
- https://github.com/jordansissel/pleaserun
- https://github.com/paulczar/chef-pleaserun

**Comment by greglu** [comment]
Thanks for the idea. I haven't been maintaining this cookbook but recently I needed to update it. With the release of [v2.0.0](https://supermarket.chef.io/cookbooks/dropwizard/), this cookbook uses the `pleaserun` gem to generate init scripts. Unfortunately the `chef-pleaserun` cookbook seems to have some bugs and also won't compile on Chef 13. I decided to use the gem directly and not have a dependency on the `chef-pleaserun` cookbook.
