### ISSUE TITLE
Parameterize the startup log file?

### ISSUE THREAD

**Issue by nukepuppy** [greglu/dropwizard-cookbook#5]
is there a specific reason the /var/log/APP_NAME is hard coded?

when we're taking control and passing in our own template  - are we able to pass in a parameterized value for the /var/log   parts

it would seem pretty logical but.. if not just making /var/log a parameterized value (attribute) would be ideal

**Comment by greglu** [comment]
No specific reason. I just didn't think through all of the configurations and dropwizard itself configures the application/access logs through the yml app config file.

I haven't been maintaining this cookbook but recently I needed to update it. With the release of [v2.0.0](https://supermarket.chef.io/cookbooks/dropwizard/), the `dropwizard` resource now has a `log_directory` property, which gets passed to the [pleaserun gem](https://github.com/jordansissel/pleaserun/blob/master/lib/pleaserun/platform/base.rb) as an attribute. Unfortunately, it doesn't look like all platforms support the attribute (systemd being one of them).

As a workaround, I recommend configuring logging through [dropwizard's configuration](http://www.dropwizard.io/1.2.2/docs/manual/core.html#id4) instead.
